### ISSUE TITLE
Security?

### ISSUE THREAD

**Issue by Xaelias** [alicebob/asprom#12]
Hi,
This doesn't have support for a user/password/credentials file?
People really run their cluster without security enabled?

Thanks :-)

**Comment by alicebob** [comment]
There is #8 but I can't test that...

**Comment by Xaelias** [comment]
Oh somehow missed it.
I can test that for you.

**Comment by alicebob** [comment]
That would be great. The person who made the original request disappeared.

So yeah, if you don't pay for enterprise you won't even have the option to use authentication, afaik.

**Comment by Xaelias** [comment]
That may be true. I'm doing this for my work and we jumped straight to the enterprise edition. Building as we speak. Will let you know in a couple minutes :-)

**Comment by Xaelias** [comment]
Doesn't look like it's working. Still not getting metrics out of asprom.
Ran:
`/tmp/asprom -username stats -listen ":9146"`
But still returns
```curl localhost:9146/metrics
# HELP aerospike_node_scrapes_total Total number of times Aerospike was scraped for metrics.
# TYPE aerospike_node_scrapes_total counter
aerospike_node_scrapes_total 2
# HELP aerospike_node_up Is this node up
# TYPE aerospike_node_up gauge
aerospike_node_up 0```

**Comment by alicebob** [comment]
ok. Which aerospike version are you using? 4?

**Comment by Xaelias** [comment]
3.15

**Comment by alicebob** [comment]
You use no password? Only a username?

**Comment by alicebob** [comment]
I added a log line when authentication fails. Could you pull the `auth` branch, build, and try again?

**Comment by Xaelias** [comment]
Yeah. Passwords are optionals.
But just tested with a user with a password, fails too.

Let me build your new version.

**Comment by Xaelias** [comment]
```
/tmp/asprom -listen ":9146" -username stats -password stats
2018/02/22 16:20:27 starting asprom. listening on :9146
2018/02/22 16:20:29 auth error: Authentication failed
```

**Comment by alicebob** [comment]
Aha. Password must be hashed. This is not a very convenient way to debug things :/

I'm working on this, will let you know... soon.

**Comment by alicebob** [comment]
Pushed a possible fix to the `auth` branch (that's the same branch as before). It now hashes the password. Sorry about the roundaboutness of this all.

(I haven't yet found a way to get a trial license from aerospike Inc)

**Comment by Xaelias** [comment]
No don't worry. Thanks for doing this :-) Testing.

**Comment by Xaelias** [comment]
Works with and without a password!
If I may have a suggestion, maybe test the authentication at startup time. But I guess that doesn't have to be.

Thanks for fixing it!
I'll keep an eye out for when you merge that back into master.

```curl localhost:9146/metrics
# HELP aerospike_node_batch_error batch error
# TYPE aerospike_node_batch_error gauge
aerospike_node_batch_error 0
# HELP aerospike_node_batch_index_complete batch index complete
# TYPE aerospike_node_batch_index_complete gauge
aerospike_node_batch_index_complete 0
...
```

**Comment by alicebob** [comment]
Thanks, good to hear!

I contacted aerospike, maybe they can give me a license so this is easier next time. I like the startup authentication test idea.

**Comment by alicebob** [comment]
Merged, a build is available on https://github.com/alicebob/asprom/releases/tag/1.1.0

**Comment by Xaelias** [comment]
Thanks!
