### ISSUE TITLE
"Missing" statistics

### ISSUE THREAD

**Issue by Xaelias** [alicebob/asprom#13]
Hey,

Since you've been so nice :-D
Any reason why you limited yourself to these metrics instead of grabbing all of them?

I am thinking specifically to 1 that is missing that we could use (but there are probably more), and that's master_objects and non_replica_objects (alongside replication-factor and effective_replication_factor).

Alexis

**Comment by alicebob** [comment]
Some of them changed over time. The ones you ask about are all per namespace, right?

**Comment by Xaelias** [comment]
Yes!
Let me know if you need more information from me.

**Comment by alicebob** [comment]
ok, will update the list. Takes a while, there are many stats :)

**Comment by Xaelias** [comment]
No problem :-) Let me know if I can help.

**Comment by alicebob** [comment]
Xaelias, I've made a PR in #14 Could you check whether all keys you want are in there (and they are correctly a gauge or a counter)?

It might be that the Enterprise edition has more keys available. In that case feel free to make a PR later :)

**Comment by alicebob** [comment]
Released as https://github.com/alicebob/asprom/releases/tag/1.2.0
