### ISSUE TITLE
prometheus.Counter's Set method is deprecated

### ISSUE THREAD

**Issue by kozl** [alicebob/asprom#2]
Hi! It seems that prometheus maintainers have changed Counter interface.

`$ go build  
./main.go:116: asc.up.Set undefined (type prometheus.Counter has no field or method Set)
./main.go:120: asc.up.Set undefined (type prometheus.Counter has no field or method Set)`

Refer to https://github.com/prometheus/client_golang/commit/3fb8ace93bc4ccddea55af62320c2fd109252880

**Comment by alicebob** [comment]
Thanks for the report. Should be solved now!
