### ISSUE TITLE
Latency metrics for batch reads?

### ISSUE THREAD

**Issue by Xaelias** [alicebob/asprom#20]
Hey,

I tried to read the latency.go code but am a bit lost.
In one of our namespaces, we mostly do batch reads. You don't include these in things like `aerospike_ops_read` (we add `aerospike_ns_batch_sub_read_success` to it currently), and I don't see latency metrics (like `aerospike_latency_read`) at all.

I was wondering if:

- metrics existed at all for the batch latencies etc.?

- can we either include them with the regular metrics, or create 2 new set of metrics:
1 for batch read/writes
1 for regular read/writes (already exist)
1 that's an aggregated view of the 2

That last one is useful because for instance right now we have:
```
sum(aerospike_ops_read) by (namespace) + sum(irate(aerospike_ns_batch_sub_read_success[5m])) by (namespace)
```
One of the problems is that for instance, on one of our namespace, we have literally 0 regular reads. We only do batch reads. Which means that the first gauge doesn't exist (until someone does a manual read on the cluster). And the sum of "undefined" + 3 is... "undefined" in prometheus.

Let me know if I can help with anything :-)

Thanks!

**Comment by alicebob** [comment]
Hi!
thanks for the explanation. I'll have to have a look at what's available exactly and will get back to you (but that won't be today).

**Comment by Xaelias** [comment]
That's great! Thanks :-)

**Comment by alicebob** [comment]
what does `asinfo -l -v latency:` give you?

I'm looking at the docs at https://www.aerospike.com/docs/operations/monitor/latency/index.html
Are you referring to the [batch-index key](https://www.aerospike.com/docs/operations/monitor/latency/index.html#batch-index) or the [batch-sub-* commands](https://www.aerospike.com/docs/operations/monitor/latency/index.html#batch-sub-start)?

Back in the day the histogram values were only available in the aerospike log file, not via the API. That changed for the basic latency values a few releases ago, so asprom reads the values via the API, but I'm still not quite sure which of the `Configuration-enabled benchmarks` are available via the API.

I do agree that the basic latency stats which are always enabled should always show up, even with a 0 value, for every namespace.

**Comment by Xaelias** [comment]
So running the asinfo command, I get things like this:
```
{ns1}-read:13:42:53-GMT,ops/sec,>1ms,>8ms,>64ms
13:43:03,73.0,0.14,0.00,0.00
{ns1}-write:13:42:53-GMT,ops/sec,>1ms,>8ms,>64ms
13:43:03,102.2,0.00,0.00,0.00
error-no-data-yet-or-back-too-small
error-no-data-yet-or-back-too-small
error-no-data-yet-or-back-too-small
{ns2}-write:13:42:53-GMT,ops/sec,>1ms,>8ms,>64ms
13:43:03,556.9,0.04,0.00,0.00
error-no-data-yet-or-back-too-small
error-no-data-yet-or-back-too-small
{ns3}-read:13:42:53-GMT,ops/sec,>1ms,>8ms,>64ms
13:43:03,11.4,0.88,0.00,0.00
{ns3}-write:13:42:53-GMT,ops/sec,>1ms,>8ms,>64ms
13:43:03,775.5,0.00,0.00,0.00
error-no-data-yet-or-back-too-small
error-no-data-yet-or-back-too-small
```

Which is not really helpfull... So you'll notice that ns2-read is not there. But the other metrics are apparently not available either...

It looks like batch-sub would be what you want to use. Whatever item(s) matche(s) the one(s) you use for regular reads.

**Comment by alicebob** [comment]
So there are two things going on:

- if there is no ns2-read row present in the output asprom won't give the prometheus key. Would it be possible to solve that in the prometeus query? Maybe with `sum(...) or 0`?

- non-default measurements such as `batch-sub` are not available via `asinfo`, but it seems only in the aerospike log file. Seems a bit of a stretch to start tailing log files, so if aerospike doesn't export the data via asinfo there is not much to do. Maybe you can ask the aerospike people how to get to that data?

**Comment by Xaelias** [comment]
Sorry I was on vacation and completely forgot to check on this ><
I'll send a quick email to support and see what they have to say :-)

**Comment by Xaelias** [comment]
'k it sounds like batch metrics can be had. But they advise not to have them on all the time (probably because of performances). So...
I guess you can close that issue.

Thanks for looking into it. And sorry for the late reply :-)

**Comment by alicebob** [comment]
Thanks for getting back :)

If you ever find some (cheap) source of the metrics let me know!

**Comment by jiayiyang** [comment]
Hi all,
I have the same question on this, can we have batch-index latency histogram in asprom? We have a namespace which only have batch read, but we cannot get related latency metrics via asprom, will this metric be supported?

**Comment by Xaelias** [comment]
Like I said last time, these metrics are just not readily available AFAIK.
I can double check (probably not this week though) and see if something changed since then though. Just harass me if I (or alicebob) doesn't come back to you :-)
