### ISSUE TITLE
./main.go:168:34: cannot use hp (type []byte) as type string in argument to conn.Authenticate

### ISSUE THREAD

**Issue by Alb0t** [alicebob/asprom#25]
Trying to fork and add the new compression-ratio metric, but can't run make. What version of go should I be using here?

https://www.aerospike.com/docs/operations/configure/namespace/storage/compression.html

```$ go version
go version go1.11.3 darwin/amd64

$ make
go build
# _/Users/alb0t/code/asprom
./main.go:168:34: cannot use hp (type []byte) as type string in argument to conn.Authenticate
make: *** [build] Error 2

**Comment by Alb0t** [comment]
I don't really know go, but I'm guessing the byte array should be converted to a string.. I'll drop a PR in and see if you think its horribly wrong or not.

**Comment by Alb0t** [comment]
Well, converting the byte array to a string seems to allow it to compile - but when I tested auth locally it failed to authenticate. Also tried running go build using go 1.10.6 and got the same error..  I'll just open a PR for my compression gauge change for now.

**Comment by alicebob** [comment]
Thanks for the issue @Alb0t. I have no problems here, with go 1.11.X. I've just pushed a version which uses the new `go mod`. If you pull and run `make`, does it compile?

I can't test the authorization myself because I don't have a licensed version of aerospike available :(

**Comment by Alb0t** [comment]
Did you add the existing authorization mechanism in there? If so, is it tested? lol
I just did a pull and yeah its building now. Awesome! 👍 thank you!

**Comment by alicebob** [comment]
> Did you add the existing authorization mechanism in there? If so, is it tested? lol

It was a PR by someone. Worked for them :)
