### ISSUE TITLE
latency: missing measurements line

### ISSUE THREAD

**Issue by LandrumLabs** [alicebob/asprom#7]
2017/10/13 16:16:27 starting asprom. listening on :9145
2017/10/13 16:16:32 latency: missing measurements line
2017/10/13 16:16:47 latency: missing measurements line

I suspect this is because we have authentication enabled.  Is there any work around?

thanks

**Comment by alicebob** [comment]
Hi, thanks for the report.

Could you try the client in the `auth` branch?
https://github.com/alicebob/asprom/tree/auth


Authentication is only supported on the enterprise version, which I don't have access to, so unfortunately I cannot test this.

**Comment by alicebob** [comment]
Merged and released in https://github.com/alicebob/asprom/releases/tag/1.1.0
