### ISSUE TITLE
relationship to asgraphite

### ISSUE THREAD

**Issue by dsw9742** [alicebob/asprom#9]
@alicebob hi Harmen, I [opened an issue over at the asgraphite repository](https://github.com/aerospike/aerospike-graphite/issues/19) about missing metrics. I had assumed that the metrics were missing due to missing implementation in the asgraphite library ... but now I am wondering if I misinterpreted the phrase "follows the logic from asgraphite" in the (asprom README)[https://github.com/alicebob/asprom/blob/master/README.md].

Is this library a reimplementation of asgraphite functionality, or does it "wrap" the asgraphite library? If the former, it appears I would be better off creating the asgraphite issue here instead of over there.

**Comment by alicebob** [comment]
It's a reimplementation of the logic, so they are independent. Any missing metrics should be added here. 

Are all the metrics you list in the other ticket relevant for you?

**Comment by alicebob** [comment]
@dsw9742 : I've updated the stats counters in #10

**Comment by dsw9742** [comment]
@alicebob this is perfect.

**Comment by alicebob** [comment]
Great! It's merged into master. There is now also a binary release available, if you want.

If you miss more stats you're intrested in do let me know; aerospike changes them quite often, and most stats I don't use, so I might miss the changes.
